# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'create.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox

import sqlite3
sql=sqlite3.connect('Game.db')
cur=sql.cursor()

#players=cur.execute("SELECT *from playerdetails WHERE Speciality=")


class Ui_createteam(object):
    def setupUi(self, createteam):
        createteam.setObjectName("createteam")
        createteam.setEnabled(True)
        createteam.resize(400, 323)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        createteam.setFont(font)
        createteam.setWindowOpacity(1.0)
        self.gridLayout = QtWidgets.QGridLayout(createteam)
        self.gridLayout.setObjectName("gridLayout")
        self.label_5 = QtWidgets.QLabel(createteam)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 4, 3, 1, 1)
        self.label_2 = QtWidgets.QLabel(createteam)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 2)
        self.listWidget1 = QtWidgets.QListWidget(createteam)
        self.listWidget1.setObjectName("listWidget1")
        self.gridLayout.addWidget(self.listWidget1, 3, 0, 1, 2)
        self.listWidget_2 = QtWidgets.QListWidget(createteam)
        self.listWidget_2.setObjectName("listWidget_2")
        self.gridLayout.addWidget(self.listWidget_2, 3, 3, 1, 2)

        self.label = QtWidgets.QLabel(createteam)
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semibold")
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.comboBox = QtWidgets.QComboBox(createteam)
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semibold")
        font.setBold(True)
        font.setWeight(75)
        self.comboBox.setFont(font)
        self.comboBox.setInputMethodHints(QtCore.Qt.ImhNone)
        self.comboBox.setEditable(False)
        self.comboBox.setMaxVisibleItems(30)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        icon = QtGui.QIcon.fromTheme("-------------")
        self.comboBox.addItem(icon, "")
        self.gridLayout.addWidget(self.comboBox, 1, 0, 1, 2)
        self.label_3 = QtWidgets.QLabel(createteam)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 3, 1, 2)
        self.label_4 = QtWidgets.QLabel(createteam)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 4, 0, 1, 1)

        self.listWidget_3 = QtWidgets.QListWidget(createteam)
        self.listWidget_3.setObjectName("listWidget_3")
        self.gridLayout.addWidget(self.listWidget_3, 3,2,1,1)

        self.label_6=QtWidgets.QLabel(createteam)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6,2,2,1,1)
        self.label_7=QtWidgets.QLabel(createteam)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7,1,2,1,1)
        self.LineEdit=QtWidgets.QLineEdit(createteam)
        self.LineEdit.setObjectName("LineEdit")
        self.gridLayout.addWidget(self.LineEdit,1,3,1,1)

        self.lcdNumber_2 = QtWidgets.QLCDNumber(createteam)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lcdNumber_2.setFont(font)
        self.lcdNumber_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.lcdNumber_2.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber_2.setObjectName("lcdNumber_2")
        self.gridLayout.addWidget(self.lcdNumber_2, 4, 4, 1, 1)
        self.lcdNumber = QtWidgets.QLCDNumber(createteam)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lcdNumber.setFont(font)
        self.lcdNumber.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.lcdNumber.setSmallDecimalPoint(False)
        self.lcdNumber.setDigitCount(5)
        self.lcdNumber.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber.setProperty("intValue", 1955)
        self.lcdNumber.setObjectName("lcdNumber")
        self.gridLayout.addWidget(self.lcdNumber, 4, 1, 1, 1)
        self.pushButton = QtWidgets.QPushButton(createteam)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 6, 2, 1, 1)
        self.pushButton1 = QtWidgets.QPushButton(createteam)
        self.pushButton1.setObjectName("pushButton1")
        self.gridLayout.addWidget(self.pushButton1, 6, 3, 1, 1)
        self.retranslateUi(createteam)
        self.comboBox.setCurrentIndex(0)


        self.comboBox.textActivated['QString'].connect(self.listWidget1.clear)
        self.current = ""

        self.comboBox.textActivated['QString'].connect(self.Availableplayers)

        #self.listWidget1.addItem("hello")

        self.listWidget1.itemDoubleClicked.connect(self.Currentplayers)
        self.listWidget_2.itemDoubleClicked.connect(self.Removeplayers)
        #self.listWidget1.itemPressed['QListWidgetItem*'].connect(self.lcdNumber.setDecMode)
        #self.listWidget1.itemDoubleClicked.connect(self.Actualscore)
        self.pushButton.clicked.connect(self.message)
        self.pushButton1.clicked.connect(createteam.close)

        self.score_left=1955
        self.score_used=0
        self.counter1=0
        self.counter2=0
        self.counter3=0
        self.counter4=0
        self.app=[]
        self.app1=[]

        QtCore.QMetaObject.connectSlotsByName(createteam)
    def message(self):
        self.c=self.counter1+self.counter2+self.counter3+self.counter4
        self.nam=self.LineEdit.text()
        team=cur.execute("SELECT Teams FROM Teams;")
        teams=team.fetchall()
        for i in teams:
            self.app1.append(i[0])



        if(self.c!=11):

            msg = QMessageBox()
            msg.setIcon(QMessageBox.Information)
            msg.setText("Team should consist of 11 Players")
            msg.setWindowTitle("Warning!!")
            msg.setStandardButtons(QMessageBox.Ok)
            msg.exec_()
        elif(self.counter1!=4 and self.counter2!=3 and self.counter3!=3 and self.counter4!=1):
            msg = QMessageBox()
            msg.setIcon(QMessageBox.Information)
            msg.setText("Team should consist of 4 Batsmen,3 Bowlers ,3 Allrounders and 1 Wicketkeeper")
            msg.setWindowTitle("Warning!!")
            msg.setStandardButtons(QMessageBox.Ok)
            msg.exec_()
        elif(self.nam==""):
            msg=QMessageBox()
            msg.setIcon(QMessageBox.Information)
            msg.setText("Enter team name!!")
            msg.setWindowTitle("Warning!!")
            msg.setStandardButtons(QMessageBox.Ok)
            msg.exec_()
        elif(self.nam in self.app1):
            msg = QMessageBox()
            msg.setIcon(QMessageBox.Information)
            msg.setText("Team name already exists!!")
            msg.setWindowTitle("Warning!!")
            msg.setStandardButtons(QMessageBox.Ok)
            msg.exec_()

        else:

            for i in self.app:

                sco=cur.execute("SELECT Score from playerdetails WHERE Playername='"+i+"';")
                scor=sco.fetchone()


                cur.execute('INSERT INTO Teams VALUES(?,?,?)',(str(self.nam),str(i),int(scor[0])))
                sql.commit()
            msg = QMessageBox()
            msg.setIcon(QMessageBox.Information)
            msg.setText("Successfully Created Team :)")
            msg.setWindowTitle("Information")
            msg.setStandardButtons(QMessageBox.Ok)
            msg.exec_()














    def Availableplayers(self):
        txt1=self.comboBox.currentText()



        player = cur.execute("SELECT * from playerdetails WHERE Speciality='"+txt1+"';")


        if(txt1!=self.current):
            for i in player:
                print(i[1])
                self.listWidget1.addItem(i[1])

        else:
            for i in player:
                if(i[1]not in self.app):
                    self.listWidget1.addItem(i[1])
        self.current=txt1

    def Currentplayers(self,item):
        self.listWidget_3.clear()

        self.listWidget1.takeItem(self.listWidget1.row(item))
        self.listWidget_2.addItem(item.text())
        self.app.append(item.text())


        score=cur.execute("SELECT Score from playerdetails WHERE playername='"+item.text()+"';")
        m=score.fetchone()
        self.score_left=self.score_left-int(m[0])
        self.score_used=self.score_used+int(m[0])
        self.lcdNumber.display(self.score_left)
        self.lcdNumber_2.display(self.score_used)


        self.listWidget_3.insertItem(0,"Batsmen:" + str(self.Playercount("Batsman",item,self.counter1)) + "")
        self.listWidget_3.insertItem(1, "Bowlers:" + str(self.Playercount("Bowler", item,self.counter2)) + "")
        self.listWidget_3.insertItem(2, "Allrounder:" + str(self.Playercount("Allrounder", item,self.counter3)) + "")
        self.listWidget_3.insertItem(3, "Wicketkeeper:" + str(self.Playercount("WicketKeeper", item,self.counter4)) + "")





        #self.teamlabe1.setText("Batsmen:")

    def Removeplayers(self,item):
        #self.listWidget_2.takeItem(self.listWidget_2.row(item))

        self.listWidget_3.clear()
        self.listWidget_2.takeItem(self.listWidget_2.row(item))
        self.app.remove(item.text())


        data=cur.execute("SELECT Speciality from playerdetails WHERE Playername = '" + item.text() + "';")
        s=data.fetchone()
        self.comboBox.setCurrentText(s[0])
        self.listWidget1.addItem(item.text())
        score = cur.execute("SELECT Score from playerdetails WHERE playername='" + item.text() + "';")
        m = score.fetchone()
        self.score_used=self.score_used-int(m[0])
        self.score_left=self.score_left+int(m[0])
        self.lcdNumber.display(self.score_left)
        self.lcdNumber_2.display(self.score_used)

        self.listWidget_3.insertItem(0, "Batsmen:" + str(self.Playercount2("Batsman", item, self.counter1)) +"")
        self.listWidget_3.insertItem(1, "Bowlers:" + str(self.Playercount2("Bowler", item, self.counter2)) + "")
        self.listWidget_3.insertItem(2, "Allrounder:" + str(self.Playercount2("Allrounder", item, self.counter3)) + "")
        self.listWidget_3.insertItem(3, "Wicketkeeper:" + str(self.Playercount2("WicketKeeper", item, self.counter4)) + "")

    def Playercount(self,cat,name,counter):

        pc=cur.execute("SELECT playername from playerdetails WHERE Speciality='"+cat+"';")
        pc1=cur.fetchall()
        list1=[]
        for i in pc1:
            list1.append(i[0])
        if(name.text()in list1 and cat=="Batsman"):
            self.counter1+=1
            counter+=1
        if (name.text() in list1 and cat == "Bowler"):
            self.counter2 += 1
            counter += 1
        if (name.text() in list1 and cat == "Allrounder"):
            self.counter3 += 1
            counter += 1
        if (name.text() in list1 and cat == "WicketKeeper"):
            self.counter4 += 1
            counter += 1

        return(counter)
    def Playercount2(self,cat,name,counter):

        pc=cur.execute("SELECT playername from playerdetails WHERE Speciality='"+cat+"';")
        pc1=cur.fetchall()
        list1=[]
        for i in pc1:
            list1.append(i[0])
        if(name.text()in list1 and cat=="Batsman"):
            self.counter1-=1
            counter-=1
        if (name.text() in list1 and cat == "Bowler"):
            self.counter2 -= 1
            counter -= 1
        if (name.text() in list1 and cat == "Allrounder"):
            self.counter3 -= 1
            counter -= 1
        if (name.text() in list1 and cat == "WicketKeeper"):
            self.counter4 -= 1
            counter -= 1

        return(counter)








    def retranslateUi(self, createteam):
        _translate = QtCore.QCoreApplication.translate
        createteam.setWindowTitle(_translate("createteam", "CreateTeam"))
        self.label_5.setText(_translate("createteam", "Points used:"))
        self.label_2.setText(_translate("createteam", "Available Players:"))
        self.label_6.setText(_translate("createteam","Players by Type:"))
        self.label_7.setText(_translate("createteam","Team name:"))

        self.label.setText(_translate("createteam", "C a t e g o r y:"))
        self.comboBox.setCurrentText(_translate("createteam", "Batsman"))
        self.comboBox.setItemText(0, _translate("createteam", "Batsman"))
        self.comboBox.setItemText(1, _translate("createteam", "Bowler"))
        self.comboBox.setItemText(2, _translate("createteam", "Allrounder"))
        self.comboBox.setItemText(3, _translate("createteam", "WicketKeeper"))
        self.label_3.setText(_translate("createteam", "Current Team:"))
        self.label_4.setText(_translate("createteam", "Available points:"))
        self.pushButton.setText(_translate("createteam", "Create"))
        self.pushButton1.setText(_translate("createteam", "Cancel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    createteam = QtWidgets.QWidget()
    ui = Ui_createteam()
    ui.setupUi(createteam)
    createteam.show()
    sys.exit(app.exec_())
