# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'open.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox

import sqlite3,time
sql=sqlite3.connect('Game.db')
cur=sql.cursor()


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(296, 300)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.comboBox = QtWidgets.QComboBox(Form)
        self.comboBox.setObjectName("comboBox")
        self.gridLayout.addWidget(self.comboBox, 0, 0, 1, 1)
        self.listWidget = QtWidgets.QListWidget(Form)
        self.listWidget.setObjectName("listWidget")
        self.gridLayout.addWidget(self.listWidget, 1, 0, 1, 1)

        self.comboBox_2 = QtWidgets.QComboBox(Form)
        self.comboBox_2.setObjectName("comboBox_2")
        self.gridLayout.addWidget(self.comboBox_2, 0, 2, 1, 1)
        self.listWidget_2 = QtWidgets.QListWidget(Form)
        self.listWidget_2.setObjectName("listWidget_2")
        self.gridLayout.addWidget(self.listWidget_2, 1, 2, 1, 1)
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setObjectName("pushButton")

        self.lcdNumber_1 = QtWidgets.QLCDNumber(Form)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lcdNumber_1.setFont(font)
        self.lcdNumber_1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.lcdNumber_1.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber_1.setObjectName("lcdNumber_1")
        self.gridLayout.addWidget(self.lcdNumber_1, 2, 0, 1, 1)

        self.lcdNumber_2 = QtWidgets.QLCDNumber(Form)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lcdNumber_2.setFont(font)
        self.lcdNumber_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.lcdNumber_2.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber_2.setObjectName("lcdNumber_2")
        self.gridLayout.addWidget(self.lcdNumber_2, 2, 2, 1, 1)

        self.gridLayout.addWidget(self.pushButton, 3, 0, 1, 1)
        self.progressBar = QtWidgets.QProgressBar(Form)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.gridLayout.addWidget(self.progressBar, 3, 2, 1, 1)

        self.pushButton.clicked.connect(self.ScoreA)

        self.retranslateUi(Form)
        self.comboBox.textActivated['QString'].connect(self.team1)
        self.comboBox_2.textActivated['QString'].connect(self.team2)
        #self.pushButton.clicked.connect(self.lineEdit.paste)
        #self.pushButton.clicked.connect(self.lineEdit_2.paste)
        self.comboBox.setDuplicatesEnabled(True)
        self.list1=[]
        self.list2=[]
        QtCore.QMetaObject.connectSlotsByName(Form)
    def team1(self):
        self.listWidget.clear()
        text1=self.comboBox.currentText()

        teams=cur.execute("SELECT PLayers,Score FROM Teams WHERE Teams='"+text1+"';")
        team_name=teams.fetchall()
        for i in team_name:
            self.list1.append(i[1])
            self.listWidget.addItem(i[0])
    def team2(self):
        self.listWidget_2.clear()
        text1 = self.comboBox_2.currentText()

        teams = cur.execute("SELECT PLayers,Score FROM Teams WHERE Teams='" + text1 + "';")
        team_name = teams.fetchall()
        for i in team_name:
            self.list2.append(i[1])
            self.listWidget_2.addItem(i[0])
    def ScoreA(self):
        self.lcdNumber_1.display(str((sum(self.list1))))

        self.lcdNumber_2.display(str((sum(self.list2))))
        list1=[]
        list2=[]
        for i in range(0,101):

            self.progressBar.setValue(i+0.1)
        self.progressBar.setValue(0)
        if(sum(self.list1)>sum(self.list2)):
            self.str="Congrats! TeamA won"
        elif(sum(self.list2)>sum(self.list1)):
            self.str="Congrats! TeamB won"
        else:
            self.str="Select Teams to start match"

        msg = QMessageBox()
        msg.setIcon(QMessageBox.Information)
        msg.setText(self.str)
        msg.setWindowTitle("Information")
        msg.setStandardButtons(QMessageBox.Ok)
        msg.exec_()

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pushButton.setText(_translate("Form", "START"))
        team=cur.execute("SELECT Teams FROM Teams;")
        teams=team.fetchall()
        self.j=0
        self.check=""
        for i in teams:

            if(self.check!=i[0]):
                self.comboBox.addItem(str(i[0]))
                self.comboBox_2.addItem(str(i[0]))
                self.j+=1
                self.check=i[0]



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
